services:
- type: web
  name: pryMongoEsp32
  runtime: python
  repo: https://github.com/Polito2007/Esp32.git
  plan: free
  envVars:
  - key: MONGO_URI
    value: mongodb+srv://Polo:Pass.word1@polo.okfw6fi.mongodb.net/myDatabase?retryWrites=true&w=majority
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
version: "1"
