services:
- type: web
  name: pryMongoEsp32
  runtime: python
  repo: https://github.com/Polito2007/Esp32.git
  plan: free
  envVars:
  - key: MONGO_URI
    value: mongodb+srv://Polo:Pass.word1@polo.okfw6fi.mongodb.net/?retryWrites=true&w=majority&appName=Polo0
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
version: "1"
#mongosh "mongodb+srv://cluster0.f4ntp.mongodb.net/" --apiVersion 1 --username jorgegil
#Dirección IP actual ( 148.215.111.122/32 ) añadida.
#Visita Acceso a la red para modificar tu configuración.  Pass.word1
